version: 0.2
phases:
  pre_build:
    commands:
      - rm -rf node_modules  # Clean up node_modules
      - rm -f package-lock.json
      - npm install  # Install dependencies
  build:
    commands:
      - npm run build  # Build your Node.js application (if required)
